# Generated by Django 5.1.4 on 2024-12-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('Mid Sem Exam', 'Mid Sem Exam'), ('Flexible Assessments', 'Flexible Assessments'), ('End Semester/Makeup Examination', 'End Semester/Makeup Examination')], max_length=50)),
                ('duration', models.CharField(help_text='Enter duration', max_length=50)),
                ('weightage', models.CharField(help_text='Enter weightage', max_length=50)),
                ('typology_of_questions', models.TextField(help_text='Enter question typology')),
                ('pattern', models.TextField(help_text='Describe the pattern')),
                ('schedule', models.CharField(help_text='Enter schedule details', max_length=50)),
                ('topics_covered', models.TextField(help_text='Enter topics covered')),
            ],
            options={
                'db_table': 'datanew',
            },
        ),
    ]
