# Generated by Django 5.1.4 on 2024-12-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcomponent',
            name='duration',
            field=models.CharField(help_text='Enter duration (e.g., 2 hours or 90 minutes)', max_length=50),
        ),
        migrations.AlterField(
            model_name='examcomponent',
            name='weightage',
            field=models.CharField(help_text='Enter weightage (percentage)', max_length=50),
        ),
    ]
